//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practice_modules.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AIRCONTROLLERS
    {
        public int ID_AIRCONTROLLERS { get; set; }
        public string NAME { get; set; }
        public string SECOND_NAME { get; set; }
        public string AGE { get; set; }
        public int ID_AIRPORT { get; set; }
    
        public virtual AIRPORTS AIRPORTS { get; set; }
    }
}
