//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practice_modules.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLIGHTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FLIGHTS()
        {
            this.PASSENGERS = new HashSet<PASSENGERS>();
        }
    
        public int ID_FLIGHT { get; set; }
        public string DEPARTURE_CITY { get; set; }
        public string ARRIVE_CITY { get; set; }
        public System.DateTime DATE_ARRIVE { get; set; }
        public int ID_PLAIN { get; set; }
        public int ID_PILOT { get; set; }
        public int ID_SECOND_PILOT { get; set; }
    
        public virtual PILOTS PILOTS { get; set; }
        public virtual PLAINES PLAINES { get; set; }
        public virtual SECOND_PILOTS SECOND_PILOTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PASSENGERS> PASSENGERS { get; set; }
    }
}
