//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practice_modules.models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AEROPORT_ModulesEntities3 : DbContext
    {
        public AEROPORT_ModulesEntities3()
            : base("name=AEROPORT_ModulesEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMINS> ADMINS { get; set; }
        public virtual DbSet<AIRCONTROLLERS> AIRCONTROLLERS { get; set; }
        public virtual DbSet<AIRPORTS> AIRPORTS { get; set; }
        public virtual DbSet<BUS> BUS { get; set; }
        public virtual DbSet<CONTROLLERS> CONTROLLERS { get; set; }
        public virtual DbSet<FLIGHTS> FLIGHTS { get; set; }
        public virtual DbSet<LOADERS> LOADERS { get; set; }
        public virtual DbSet<PASSENGERS> PASSENGERS { get; set; }
        public virtual DbSet<PILOTS> PILOTS { get; set; }
        public virtual DbSet<PLAINES> PLAINES { get; set; }
        public virtual DbSet<ROLES> ROLES { get; set; }
        public virtual DbSet<SECOND_PILOTS> SECOND_PILOTS { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<USERS> USERS { get; set; }
    }
}
